version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    groups:
      production-updates:
        dependency-type: "production"
      development-updates:
        dependency-type: "development"