services:
  eyerdocker:
    image: eyerai/eyerdocker:1.2.2
    container_name: eyerdocker
    environment:
      BOOMI_USERNAME: "BOOMI_TOKEN.insert_your_email"
      BOOMI_TOKEN: "your_boomi_token"
      BOOMI_ACCOUNT_ID: "your_account_id"
      BOOMI_ATOM_IP: 0.0.0.0
#      BOOMI_ATOM_IP: |
#        192.168.2.1:1233|service_name
#        192.168.2.2
      EYER_PUSH_TOKEN: "insert_your_eyer_push_token"
    restart: always
