name: Build and Publish Docker Image

on:
  workflow_dispatch: 
  push:
    branches:
      - master
    paths:
      - 'docker/**'
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker tags
        id: docker_tags
        run: |
          # Start with master tag
          TAGS="eyerai/eyerdocker:master"
          
          # If this is a tag push, add version and latest tags
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            # Extract tag name without the 'v' prefix
            VERSION=${GITHUB_REF#refs/tags/v}
            TAGS="$TAGS,eyerai/eyerdocker:$VERSION,eyerai/eyerdocker:latest"
            echo "Tagged with version $VERSION and latest"
          fi
          
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
